EDU.Web/Controllers/ReportsController.cs
using EDU.Web;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;


namespace EDU.Web.Reports.Controllers
{
    //[RouteArea("Reports")]
    //[ActionFilters.SessionFilter]
    public class ReportsController : BaseController
    {
        // GET: Reports
        public ActionResult MaterialInward()
        {
            ViewBag.LoginID = BRANCH_ID;
            return View();
        }
        //public ActionResult MaterialInwards(string dateFrom, string dateTo)
        //{
        //    ViewBag.DateFrom = "01/09/2017";
        //    ViewBag.DateTo = "25/09/2017";
        //    ViewBag.ReportSource = "MaterialInwardReport";
        //    ViewBag.BranchID = BRANCH_ID;
        //    ViewBag.Url = string.Format("{0}{1}{2}", "http://sql5002.smarterasp.net/ReportServer", UTILITY.REPORTSUBFOLDER,"/RMAReports/MaterialInwardSSRSReport?BranchID=10&DateFrom=08/09/2017&DateTo=09/25/2017");
        //    var path = "~/Views/Shared/_ReportViewerPartial.cshtml";
        //    return PartialView(path);
        //}
        public ActionResult MaterialInwards(int branchID, string dateFrom, string dateTo)
        {
            string url = "MaterialInwardSSRSReport";
            NetworkCredential nwc = new NetworkCredential("ragsarma-001", "n0ki@3310", "ifc");
            WebClient client = new WebClient();
            client.Credentials = nwc;
            string reportURL = string.Format("{0}?{1}{2}&rs:Command=Render&rs:Format=PDF&rc:Toolbar=false&rc:Parameters=false&BranchID={3}&DateFrom={4}&DateTo={5}", "http://sql5002.smarterasp.net/ReportServer",
                "/ragsarma-001/RMAReports/", url, branchID, dateFrom, dateTo);
            var cd = new System.Net.Mime.ContentDisposition
            {
                FileName = "Report.pdf",
                Inline = false,
            };
            Response.AppendHeader("Content-Disposition", cd.ToString());

            return File(client.DownloadData(reportURL), "application/pdf");
        }
        public ActionResult ManagementReports()
        {
            return View();
        }

        public ActionResult Achievement()
        {
            return View();
        }
        public ActionResult Operationaltransaction()
        {
            return View();
        }
        public ActionResult OperationalExpenses()
        {
            return View();
        }

    }
}

EDU.Web/Views/Reports/ManagementReports.cshtml
@{
    ViewBag.Title = "ManagementReports";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<style>
    .rpts {
       font-size:20px;
       align-content:center;
    }
    .Dashboard{
        padding-left:50px;
    }
    .Dashboard2{
        padding-left:150px;
    }
     .Dashboard3{
        padding-left:270px;
    }
         .Dashboard4{
        padding-left:380px;
    }
</style>
<section class="content">
    <div class="box box-default">
        <div class="box-header with-border">
            <div class="row">
                <section class="content-header">
                    <ol class="breadcrumb">
                        <li><a href='@Url.Content("~/Home/Modules")'><i class="fa fa-dashboard"></i> Home</a></li>
                        <li><a href='@Url.Content("~/Home/Index")'>Modules</a></li>
                        <li><a href='@Url.Content("~/Home/Reports")'> Reports</a></li>
                        <li class="active">Management Reports</li>
                    </ol>
                </section>
            </div>
        </div>
        <div class="box-body rpts">
            <div class="row css10">
                <div class="col-md-6 Dashboard">
                    @Html.ActionLink("Dashboard", "Dashboard", "Home")
                </div>
            </div>
            <br />
            <div class="row css10">
                <div class="col-md-6 Dashboard">
                    @Html.ActionLink("Dashboard2", "Dashboard2", "Home")
                </div>
            </div>
            <br />
            <div class="row css10">
                <div class="col-md-6 Dashboard">
                    @Html.ActionLink("Dashboard3", "Dashboard3", "Home")
                </div>
            </div>
            <br />
            <div class="row css10">
                <div class="col-md-6 Dashboard">
                    @Html.ActionLink("Dashboard4", "Dashboard4", "Home")
                </div>
            </div>
        </div>
        <div class="box-footer">
            <div class="row">
                <div class="col-md-12">
                    <button class="btn btn-default btn-sm pull-right" type="button" onclick="location.href = '@Url.Content("~/Home/Reports")'"><i class="fa fa-backward"></i>&nbsp;Back</button>
                </div>

            </div>
        </div>
    </div>
</section>

EDU.Web/Views/Reports/MaterialInward.cshtml
@model EZY.EDU.Contract.ReportParams


@section seccss{
    @*<link href="@Url.Content("~/Css/datepicker3.css")" rel="stylesheet" />
        <link href="@Url.Content("~/Css/bootstrap-timepicker.css")" rel="stylesheet" />*@
    <link href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datetimepicker/4.17.47/css/bootstrap-datetimepicker.css" rel="stylesheet">
}
<div class="modal fade in" id="myModal">
    <div class="modal-dialog">
        <div class="modal-content">
            <div id='myModalContent'></div>
        </div>
    </div>
</div>
<section class="content">
    @using (Html.BeginForm("MaterialInwards", "Reports", FormMethod.Post, new { id = "frmReportInward", name = "frmReportInward" }))
    {
        <div class="box box-dnex">
            <div class="box-header with-border">
                <div class="row">
                    <section class="content-header">
                        <ol class="breadcrumb">
                            <li><a href='@Url.Content("~/Home/Modules")'><i class="fa fa-dashboard"></i> Home</a></li>
                            <li><a href='@Url.Content("~/Home/Index")'>Modules</a></li>
                            <li><a href='@Url.Content("~/Home/Reports")'> Reports</a></li>
                            <li class="active">Operational Reports</li>
                        </ol>
                    </section>
                </div>
            </div>
            <div class="box-body">
                <div class="row css10">
                    <div class="col-md-2">
                        <label class="control-label pull-right">Branch ID&nbsp; <span class="error-req">*</span></label>
                    </div>
                    <div class="col-md-2">
                        @Html.TextBoxFor(x => x.BranchID, new { @class = "form-control input-sm", @readonly = "readonly", @Value = ViewBag.LoginID })
                    </div>
                </div>
                <div class="row css10">
                    <div class="col-md-2">
                        <label class="control-label pull-right">Date From&nbsp; <span class="error-req">*</span></label>
                    </div>
                    <div class="col-md-2">
                        <div class="input-group date" id="InvoiceDt">
                            @Html.TextBoxFor(x => x.DateFrom, new { @class = "form-control input-sm" })
                            <span class="input-group-addon">
                                <span class="fa fa-calendar"></span>
                            </span>
                        </div>
                    </div>
                </div>
                <div class="row css10">
                    <div class="col-md-2">
                        <label class="control-label pull-right">Date To&nbsp; <span class="error-req">*</span></label>
                    </div>
                    <div class="col-md-2">
                        <div class="input-group date" id="InvoiceDts">
                            @Html.TextBoxFor(x => x.DateTo, new { @class = "form-control input-sm" })
                            <span class="input-group-addon">
                                <span class="fa fa-calendar"></span>
                            </span>
                        </div>
                    </div>
                </div>
            </div>
            <div class="box-footer">
                <div class="row">
                    <div class="col-xs-12">
                        <div class="col-md-12">
                            @Html.ActionLink("Print", "MaterialInward", "Reports", new { id = "btnViewReport", onclick = "PrintClick()", @class = "btn btn-sm btn-primary" })
                            <button class="btn btn-default btn-sm pull-right" type="button" onclick="location.href = '@Url.Content("~/Home/Reports")'"><i class="fa fa-backward"></i>&nbsp;Back</button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    }
</section>

@section secscripts {
    <script src="@Url.Content("~/Scripts/moment.min.js")"></script>
    <script src="@Url.Content("~/Scripts/bootstrap-datetimepicker.js")"></script>
    <script type="text/javascript">
        $(function () {
            $('#frmReportInward').validate({
                rules: {
                    BranchID: {
                        required: true
                    },
                    DateFrom:{
                        required:true
                    },
                    DateTo: {
                        required:true
                    }
                }
            });
        });
        $('#InvoiceDt').datetimepicker({
            icons: {
                time: 'fa fa-clock-o',
                date: 'fa fa-calendar',
                up: 'fa fa-arrow-up',
                down: 'fa fa-arrow-down'
            },
            format: 'MM/DD/YYYY'
        });
        $('#InvoiceDts').datetimepicker({
            icons: {
                time: 'fa fa-clock-o',
                date: 'fa fa-calendar',
                up: 'fa fa-arrow-up',
                down: 'fa fa-arrow-down'
            },
            format: 'MM/DD/YYYY'
        });
        function PrintClick() {
            if ($('#frmReportInward').valid()) {
                var CustomerCode = $("#ddlCustomerCode").val();
                var dateFrom = ($("#DateFrom").val());
                var dateTo = ($("#DateTo").val());
                var ReportURL = ("/RMAReports/MaterialInwardReport");
                var branchID = $('#BranchID').val();
                debugger;
                var rooturl = '@Url.Action("MaterialInwards", "Reports")';
                var url = rooturl + "?dateFrom=" + dateFrom + "&dateTo=" + dateTo + "&URL=" + ReportURL;
                if (branchID != '')
                    url += "&branchID=" + branchID;
                $("#btnViewReport").attr("href", url);
            }
        }
        //$("#ddlCustomerCode").select2();
    </script>
}

EDU.Web/Views/Reports/MaterialInward1.cshtml
@model EZY.EDU.Contract.ReportParams

@{
    ViewBag.Title = "MaterialInward";
}

@section css{
<link href="@Url.Content("~/Css/dataTables.bootstrap.css")" rel="stylesheet" />
<link href="@Url.Content("~/Css/bootstrap-timepicker.css") "rel="stylesheet" />
<link href="@Url.Content("~/Css/dataTables.responsive.css")" rel="stylesheet" />
<link href="@Url.Content("~/Css/style.min.css")" rel="stylesheet" />
}
<div class="modal fade in" id="myModal">
    <div class="modal-dialog">
        <div class="modal-content">
            <div id='myModalContent'></div>
        </div>
    </div>
</div>
<section class="content">
    @using (Html.BeginForm("MaterialInwards", "Reports", FormMethod.Post))
    {
        @*@using (Ajax.BeginForm("ViewReportDailySales", "Reports", new AjaxOptions { HttpMethod = "POST", OnBegin = "OpenPopup", OnSuccess = "OnSaveSuccess", OnFailure = "OnSaveFailure" }, new { Area = "Reports", enctype = "multipart/form-data", id = "myForm" }))
            {*@

        <div class="box box-solid box-default">
            <div class="box-header with-border">
                <h3 class="box-title">Daily Sales</h3>

            </div>
            <div class="box-body">
                <fieldset class="form-horizontal">
                    @*<div class="form-group">
                            <div>
                                <label class="col-md-2 input-sm control-label">Branch</label>
                                <div class="col-md-4">
                                    @Html.DropDownList("BranchID", new SelectList(ViewBag.BranchList, "Value", "Text"), "All", new { @class = "form-control input-sm" })
                                </div>
                            </div>
                        </div>*@
                    <div class="form-group">
                        <div>
                            <label class="col-md-2 control-label input-sm">Date From</label>
                            <div class="col-sm-2">
                                @Html.TextBoxFor(m => m.DateFrom, new { @class = "form-control input-sm datepicker" })
                            </div>
                            <label class="col-md-2 control-label input-sm">Date To</label>
                            <div class="col-sm-2">
                                @Html.TextBoxFor(m => m.DateTo, new { @class = "form-control input-sm datepicker" })

                            </div>
                        </div>
                    </div>
                </fieldset>
            </div>
            <div class="box-footer">
                <div class="row  no-print">
                    <div class="col-xs-12">
                        <div class="btn-group dropup">
                            @*the URL need to be the Datasource url*@
                            @*@Html.ActionLink("Print", "MaterialInward", "Reports", new { }, new { data_modal = "test", id = "btnViewReport", onclick = "PrintClick()", @class = "btn btn-sm btn-primary" })*@
                            <a id="btnViewReport" data-modal="test" onclick="PrintClick();" class="btn btn-sm btn-primary">Print ddf</a>
                        </div>
                        <a href="@Url.Content("~/Dashboard/Index")" id="btnBack" class="btn btn-sm btn-info pull-right">
                            <i class="fa fa-arrow-circle-o-left"></i>
                            Back
                        </a>
                    </div>
                </div>
            </div>
        </div>
    }
</section>

@section Scripts {

    @*@Scripts.Render("~/bundles/modalform")*@
<script src="@Url.Content("~/Scripts/jquery.dataTables.js")"></script>
<script src="@Url.Content("~/Scripts/dataTables.bootstrap.js")"></script>
<script src="@Url.Content("~/Scripts/moment.js")"></script>
<script src="@Url.Content("~/Scripts/bootstrap-datetimepicker.js")"></script>

    <script type="text/javascript">


        function PrintClick() {

            var CustomerCode = $("#ddlCustomerCode").val();
            var dateFrom = ($("#DateFrom").val());
            var dateTo = ($("#DateTo").val());
            var ReportURL = ("/RMAReports/MaterialInwardReport");
            var branchID = $('#BranchID').val();
            debugger;
            var rooturl = '@Url.Action("MaterialInwardReport", "Reports", new { area = "Reports" })';
            var url = rooturl + "?dateFrom=" + dateFrom + "&dateTo=" + dateTo + "&URL=" + ReportURL;
            if (branchID != '')
                url += "&branchID=" + branchID;
            debugger
            $("#btnViewReport").attr("href", url);
        }

        //$("#ddlCustomerCode").select2();

        $(function () {

            $('.datepicker').datetimepicker({
                useCurrent: false,
                format: 'DD/MM/YYYY',
                inline: false
            });
        });

    </script>
}

EDU.Web/Views/Reports/OperationalExpenses.cshtml
@{
    ViewBag.Title = "OperationalExpenses";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<script src="https://code.highcharts.com/highcharts.js"></script>
<script src="https://code.highcharts.com/highcharts-3d.js"></script>
<script src="https://code.highcharts.com/modules/exporting.js"></script>
<script src="http://www.jqchart.com/jquery/chart/Scripts/jquery-1.11.1.min.js" type="text/javascript"></script>
<script src="http://www.jqchart.com/jquery/chart/Scripts/jquery-ui-1.10.4.min.js" type="text/javascript"></script>
<script src="http://www.jqchart.com/jquery/chart/Scripts/jquery.jqRangeSlider.min.js" type="text/javascript"></script>
<script src="http://www.jqchart.com/jquery/chart/Scripts/jquery.jqChart.min.js" type="text/javascript"></script>
<script src="http://www.jqchart.com/jquery/chart/Scripts/jquery.mousewheel.js" type="text/javascript"></script>
<script src="http://www.jqchart.com/jquery/chart/Scripts/prettify.js" type="text/javascript"></script>


<section class="content">
    <div class="box">
        <div class="box-header with-border">

            <div class="row">
                <section class="content-header">
                    <ol class="breadcrumb">
                        <li><a href='@Url.Content("~/Home/Education")'><i class="fa fa-dashboard"></i> Home</a></li>
                    </ol>
                </section>
            </div>

        </div>
            <h3 class="box-title" style="text-align:center">
                &nbsp;Dashboard - Operational Expenses
            </h3>
            <div class="box-body">
                <div class="row">
                    <div class="col-md-12">
                        @*<div class="row">
                            <h2>YTD</h2>
                        </div>*@
                    </div>
                    <div class="col-md-12">
                        <div class="col-md-6">
                            <div class="row">
                                <div class="col-md-8">
                                    <div id="jqChart"></div>
                                </div>
                            </div>
                            <div class="row css10">
                                <div class="col-md-8">
                                    <div id="jqChart1"></div>
                                </div>
                            </div>
                            <div class="row css10">
                                <div class="col-md-8">
                                    <div id="jqChart2"></div>
                                </div>
                            </div>
                            <div class="row css10">
                                <div class="col-md-8">
                                    <div id="jqChart3"></div>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="row">
                                <div class="col-md-8">
                                    <div id="jqChart4"></div>
                                </div>
                            </div>
                            <div class="row css10">
                                <div class="col-md-8">
                                    <div id="jqChart5"></div>
                                </div>
                            </div>
                            <div class="row css10">
                                <div class="col-md-8">
                                    <div id="jqChart6"></div>
                                </div>
                            </div>
                            <div class="row css10">
                                <div class="col-md-8">
                                    <div id="jqChart7"></div>
                                </div>
                            </div>
                        </div>

                    </div>

                </div>
            </div>
        </div>
  
</section>
<script type="text/javascript">
    $(document).ready(function () {
        $('#jqChart').jqChart({
            title: { text: '' },
            animation: { duration: 1 },
            shadows: {
                enabled: true
            },
            series: [
                {
                    type: 'column',
                    title: 'CAMBODIA',
                    fillStyles: ['#191970', '#191970', '#191970', '#191970', '#191970', '#191970', '#191970', '#191970', '#191970', '#191970', '#191970', '#191970', '#191970'],
                    data: [['JAN', 33], ['FEB', 57], ['MAR', 33],
                           ['APR', 12], ['MAY', 35], ['JUN', 7], ['JUL', 24],
                    ['AUG', 12], ['SEP', 35], ['OCT', 7], ['NOV', 24], ['DEC', 24]
                    ]
                }
            ]
        });
    });
</script>
<script type="text/javascript">
    $(document).ready(function () {
        $('#jqChart1').jqChart({
            title: { text: '' },
            animation: { duration: 1 },
            shadows: {
                enabled: true
            },
            series: [
                {
                    type: 'column',
                    title: 'MYANMAR',
                    fillStyles: ['#191970', '#191970', '#191970', '#191970', '#191970', '#191970', '#191970', '#191970', '#191970', '#191970', '#191970', '#191970', '#191970'],
                    data: [['JAN', 33], ['FEB', 57], ['MAR', 33],
                           ['APR', 12], ['MAY', 35], ['JUN', 7], ['JUL', 24],
                    ['AUG', 12], ['SEP', 35], ['OCT', 7], ['NOV', 24], ['DEC', 24]
                    ]
                }
            ]
        });
    });
</script>
<script type="text/javascript">
    $(document).ready(function () {
        $('#jqChart2').jqChart({
            title: { text: '' },
            animation: { duration: 1 },
            shadows: {
                enabled: true
            },
            series: [
                {
                    type: 'column',
                    title: 'PAKISTAN',
                    fillStyles: ['#191970', '#191970', '#191970', '#191970', '#191970', '#191970', '#191970', '#191970', '#191970', '#191970', '#191970', '#191970', '#191970'],
                    data: [['JAN', 33], ['FEB', 57], ['MAR', 33],
                           ['APR', 12], ['MAY', 35], ['JUN', 7], ['JUL', 24],
                    ['AUG', 12], ['SEP', 35], ['OCT', 7], ['NOV', 24], ['DEC', 24]
                    ]
                }
            ]
        });
    });
</script>
<script type="text/javascript">
    $(document).ready(function () {
        $('#jqChart3').jqChart({
            title: { text: '' },
            animation: { duration: 1 },
            shadows: {
                enabled: true
            },
            series: [
                {
                    type: 'column',
                    title: 'LAOS',
                    fillStyles: ['#191970', '#191970', '#191970', '#191970', '#191970', '#191970', '#191970', '#191970', '#191970', '#191970', '#191970', '#191970', '#191970'],
                    data: [['JAN', 33], ['FEB', 57], ['MAR', 33],
                           ['APR', 12], ['MAY', 35], ['JUN', 7], ['JUL', 24],
                    ['AUG', 12], ['SEP', 35], ['OCT', 7], ['NOV', 24], ['DEC', 24]
                    ]
                }
            ]
        });
    });
</script>
<script type="text/javascript">
    $(document).ready(function () {
        $('#jqChart4').jqChart({
            title: { text: '' },
            animation: { duration: 1 },
            shadows: {
                enabled: true
            },
            series: [
                {
                    type: 'column',
                    title: 'BANGLADESH',
                    fillStyles: ['#191970', '#191970', '#191970', '#191970', '#191970', '#191970', '#191970', '#191970', '#191970', '#191970', '#191970', '#191970', '#191970'],
                    data: [['JAN', 33], ['FEB', 57], ['MAR', 33],
                           ['APR', 12], ['MAY', 35], ['JUN', 7], ['JUL', 24],
                    ['AUG', 12], ['SEP', 35], ['OCT', 7], ['NOV', 24], ['DEC', 24]
                    ]
                }
            ]
        });
    });
</script>
<script type="text/javascript">
    $(document).ready(function () {
        $('#jqChart5').jqChart({
            title: { text: '' },
            animation: { duration: 1 },
            shadows: {
                enabled: true
            },
            series: [
                {
                    type: 'column',
                    title: 'SRI LANKA',
                    fillStyles: ['#191970', '#191970', '#191970', '#191970', '#191970', '#191970', '#191970', '#191970', '#191970', '#191970', '#191970', '#191970', '#191970'],
                    data: [['JAN', 33], ['FEB', 57], ['MAR', 33],
                           ['APR', 12], ['MAY', 35], ['JUN', 7], ['JUL', 24],
                    ['AUG', 12], ['SEP', 35], ['OCT', 7], ['NOV', 24], ['DEC', 24]
                    ]
                }
            ]
        });
    });
</script>
<script type="text/javascript">
    $(document).ready(function () {
        $('#jqChart6').jqChart({
            title: { text: '' },
            animation: { duration: 1 },
            shadows: {
                enabled: true
            },
            series: [
                {
                    type: 'column',
                    title: 'PHILIPPINES',
                    fillStyles: ['#191970', '#191970', '#191970', '#191970', '#191970', '#191970', '#191970', '#191970', '#191970', '#191970', '#191970', '#191970', '#191970'],
                    data: [['JAN', 33], ['FEB', 57], ['MAR', 33],
                           ['APR', 12], ['MAY', 35], ['JUN', 7], ['JUL', 24],
                    ['AUG', 12], ['SEP', 35], ['OCT', 7], ['NOV', 24], ['DEC', 24]
                    ]
                }
            ]
        });
    });
</script>
<script type="text/javascript">
    $(document).ready(function () {
        $('#jqChart7').jqChart({
            title: { text: '' },
            animation: { duration: 1 },
            shadows: {
                enabled: true
            },
            series: [
                {
                    type: 'column',
                    title: 'VIETNAM',
                    fillStyles: ['#191970', '#191970', '#191970', '#191970', '#191970', '#191970', '#191970', '#191970', '#191970', '#191970', '#191970', '#191970', '#191970'],
                    data: [['JAN', 33], ['FEB', 57], ['MAR', 33],
                           ['APR', 12], ['MAY', 35], ['JUN', 7], ['JUL', 24],
                    ['AUG', 12], ['SEP', 35], ['OCT', 7], ['NOV', 24], ['DEC', 24]
                    ]
                }
            ]
        });
    });
</script>

EDU.Web/Views/Reports/Operationaltransaction.cshtml
@{
    ViewBag.Title = "Operationaltransaction";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<script src="https://code.highcharts.com/highcharts.js"></script>
<script src="https://code.highcharts.com/highcharts-3d.js"></script>
<script src="https://code.highcharts.com/modules/exporting.js"></script>
<script src="http://www.jqchart.com/jquery/chart/Scripts/jquery-1.11.1.min.js" type="text/javascript"></script>
<script src="http://www.jqchart.com/jquery/chart/Scripts/jquery-ui-1.10.4.min.js" type="text/javascript"></script>
<script src="http://www.jqchart.com/jquery/chart/Scripts/jquery.jqRangeSlider.min.js" type="text/javascript"></script>
<script src="http://www.jqchart.com/jquery/chart/Scripts/jquery.jqChart.min.js" type="text/javascript"></script>
<script src="http://www.jqchart.com/jquery/chart/Scripts/jquery.mousewheel.js" type="text/javascript"></script>
<script src="http://www.jqchart.com/jquery/chart/Scripts/prettify.js" type="text/javascript"></script>

<section class="content">
    <div class="box">
        <div class="box-header with-border">

            <div class="row">
                <section class="content-header">
                    <ol class="breadcrumb">
                        <li><a href='@Url.Content("~/Home/Education")'><i class="fa fa-dashboard"></i> Home</a></li>
                    </ol>
                </section>
            </div>
            
        </div>
        <h3 class="box-title" style="text-align:center">&nbsp;Operational transaction</h3>
        <div class="box-body">
            <div class="row">
                <div class="col-md-12">
                    <div class="col-md-6">
                        <div class="row">
                            <div class="col-md-2">
                                <label>MTD</label>
                            </div>
                            <div class="col-md-5">
                                Dropdownlist <select></select>
                            </div>
                            <div class="col-md-5">
                                Dropdownlist<select>
                                    Dropdownlist
                                </select>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-12">
                                <div id="container"></div>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="row">
                            <div class="col-md-12" style="text-align:center">
                                <h2>
                                    <label>YTD</label>
                                </h2>
                            </div>

                        </div>
                        <div class="row">
                            <div class="col-md-10">
                                <div id="jqChart"></div>
                            </div>
                        </div>

                    </div>

                </div>
            </div>
        </div>
    </div>
</section>
<style>
    .highcharts-button-symbol {
        display: none;
    }
</style>
<script type="text/javascript">
    Highcharts.chart('container', {
        chart: {
            type: 'pie',
            options3d: {
                enabled: true,
                alpha: 45,
                beta: 0
            }
        },
        title: {
            text: ''
        },
        tooltip: {
            pointFormat: '{series.name}: <b>{point.percentage:.1f}%</b>'
        },
        plotOptions: {
            pie: {
                allowPointSelect: true,
                cursor: 'pointer',
                depth: 35,
                dataLabels: {
                    enabled: true,
                    format: '{point.name}'
                }
            }
        },
        series: [{
            type: 'pie',
            name: 'Browser share',
            data: [
                ['Firefox', 45.0],
                ['IE', 26.8],
                {
                    name: 'Chrome',
                    y: 12.8,
                    sliced: true,
                    selected: true
                },
                ['Safari', 8.5],
                ['Opera', 6.2],
                ['Others', 0.7]
            ]
        }]
    });
</script>
<script type="text/javascript">
    $(document).ready(function () {
        $('#jqChart').jqChart({
            title: { text: '' },
            animation: { duration: 1 },
            shadows: {
                enabled: true
            },
            series: [
                {
                    type: 'column',
                    title: '',
                    fillStyles: ['#191970', '#191970', '#191970', '#191970', '#191970', '#191970', '#191970', '#191970', '#191970', '#191970', '#191970', '#191970', '#191970'],
                    data: [['JAN', 33], ['FEB', 57], ['MAR', 33],
                           ['APR', 12], ['MAY', 35], ['JUN', 7], ['JUL', 24],
                    ['AUG', 12], ['SEP', 35], ['OCT', 7], ['NOV', 24], ['DEC', 24]
                    ]
                }
            ]
        });
    });
</script>