EDU.Web/Controllers/RMAController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using EZY.EDU.Contract;
using EZY.EDU.BusinessFactory;
using System.Threading.Tasks;
using System.IO;
using System.Web.Hosting;
using System.Globalization;
using LogiCon.Utilities;

namespace EDU.Web.Controllers
{
    [WebSsnFilter]
    public class RMAController : BaseController
    {
        public Task MessageServices { get; private set; }


        public ActionResult Inward()
        {
            ViewBag.countries = new CountryBO().GetList().Select(x => new
            {
                Value = x.CountryCode,
                Text = x.CountryName
            }).ToList();
            return View(new RMAHeader { IncidentDate = UTILITY.SINGAPORETIME });
        }
        public ActionResult VendorRMA()
        {
            ViewBag.countries = new CountryBO().GetList().Select(x => new
            {
                Value = x.CountryCode,
                Text = x.CountryName
            }).ToList();
            return View(new VendorRMAHeader { IncidentDate = UTILITY.SINGAPORETIME });
        }
        public ActionResult ProcessVendorRMA(VendorRMAHeader vendorRmaHeader)
        {
            if (vendorRmaHeader.VendorRmaDetails == null)
            {
                return RedirectToAction("VendorRMA");
            }
            else
            {
                for (var i = 0; i < vendorRmaHeader.VendorRmaDetails.Count; i++)
                {
                    var VendorRmaInwardDTO = new InvoiceDetailBO().GetVendorDetailBySerialNo(vendorRmaHeader.VendorRmaDetails[i].SerialNo, BRANCH_ID, UTILITY.CONFIG_INVOICETYPE_VENDOR);//CONFIG_INVOICETYPE_CUSTOMER

                    if (VendorRmaInwardDTO != null)
                    {
                        vendorRmaHeader.VendorRmaDetails[i].VendorInvoiceNo = VendorRmaInwardDTO.VendorInvoiceNo;
                        vendorRmaHeader.VendorRmaDetails[i].VendorName = VendorRmaInwardDTO.VendorName;
                        vendorRmaHeader.VendorRmaDetails[i].DocumentNo = VendorRmaInwardDTO.DocumentNo;
                        vendorRmaHeader.VendorRmaDetails[i].WarrantyExpiryDate = VendorRmaInwardDTO.CustomerWarrantyExpiryDate;
                        vendorRmaHeader.VendorRmaDetails[i].IsValid = (UTILITY.SINGAPORETIME < vendorRmaHeader.VendorRmaDetails[i].WarrantyExpiryDate);
                        if (VendorRmaInwardDTO.VendorWarrantyExpiryDate != null)
                        {
                            vendorRmaHeader.VendorRmaDetails[i].RMAIsValid = (UTILITY.SINGAPORETIME < VendorRmaInwardDTO.VendorWarrantyExpiryDate);
                            vendorRmaHeader.VendorRmaDetails[i].VendorWarrantyExpiryDate = VendorRmaInwardDTO.VendorWarrantyExpiryDate;
                        }
                    }
                    else
                    {
                        vendorRmaHeader.VendorRmaDetails[i].IsValid = false;
                    }
                }
                ViewBag.countries = new CountryBO().GetList().Select(x => new
                {
                    Value = x.CountryCode,
                    Text = x.CountryName
                }).ToList();
                return View("VendorRMA", vendorRmaHeader);


            }
        }
        public ActionResult ProcessRMAInward(RMAHeader rmaHeader)
        {
            if (rmaHeader.rmaDetails == null)
            {
                return RedirectToAction("Inward");
            }
            else
            {
                for (var i = 0; i < rmaHeader.rmaDetails.Count; i++)
                {
                    //Comment by krishna 31/08/2017 
                    //  var rmaInwardDTO = new InvoiceDetailBO().GetVendorInvoiceDetailBySerialNo(rmaHeader.rmaDetails[i].SerialNo, BRANCH_ID, UTILITY.CONFIG_INVOICETYPE_VENDOR);//CONFIG_INVOICETYPE_CUSTOMER
                    var rmaInwardDTO = new InvoiceDetailBO().GetVendorInvoiceDetailBySerialNo(rmaHeader.rmaDetails[i].SerialNo, BRANCH_ID, UTILITY.CONFIG_INVOICETYPE_CUSTOMER);//CONFIG_INVOICETYPE_CUSTOMER
                    if (rmaInwardDTO != null)
                    {
                        rmaHeader.rmaDetails[i].DocumentNo = rmaInwardDTO.DocumentNo;
                        rmaHeader.rmaDetails[i].WarrantyExpiryDate = rmaInwardDTO.InvoiceDate.AddMonths(rmaInwardDTO.WarrantyPeriod);
                        rmaHeader.rmaDetails[i].IsValid = (UTILITY.SINGAPORETIME < rmaHeader.rmaDetails[i].WarrantyExpiryDate);
                    }
                    else
                    {
                        rmaHeader.rmaDetails[i].IsValid = false;
                    }
                }
            }

            ViewBag.countries = new CountryBO().GetList().Select(x => new
            {
                Value = x.CountryCode,
                Text = x.CountryName
            }).ToList();

            return View("Inward", rmaHeader);
        }
        //[HttpPost]
        //[AllowAnonymous]
        //public async Task<ActionResult> SendEmail(RMAHeader model)
        //{
        //    var message = await EMailTemplate("WelcomeEmail");
        //    message = message.Replace("@ViewBag.Name", CultureInfo.CurrentCulture.TextInfo.ToTitleCase(model.EmailID));
        //    await EmailGenerator.SendEmailAsync(model.EmailID, "Welcome!", message);
        //    return View("EmailSent");
        //}
        public ActionResult EmailSent()
        {
            return View();
        }
        public static async Task<string> EMailTemplate(string template)
        {
            var templateFilePath = HostingEnvironment.MapPath("~/Css/templates/") + template + ".cshtml";
            StreamReader objstreamreaderfile = new StreamReader(templateFilePath);
            var body = await objstreamreaderfile.ReadToEndAsync();
            objstreamreaderfile.Close();
            return body;
        }

        public ActionResult GenerateRMA(RMAHeader rmaHeader)
        {

            rmaHeader.rmaDetails = rmaHeader.rmaDetails.Where(x => x.IsValid == true).ToList();
            rmaHeader.Status = true;
            rmaHeader.CreatedBy = USER_ID;
            rmaHeader.CreatedOn = UTILITY.SINGAPORETIME;
            rmaHeader.ModifiedBy = USER_ID;
            rmaHeader.ModifiedOn = UTILITY.SINGAPORETIME;
            rmaHeader.IncidentDate = UTILITY.SINGAPORETIME;
            var result = new RMAHeaderBO().SaveRMAHeader(rmaHeader, BRANCH_ID);
            string documentNo = rmaHeader.rmaDetails.FirstOrDefault().DocumentNo;
            List<RMADetail> rmaDetails = new RMADetailBO().GetListByDocumentNo(documentNo);
            List<string> serialNos = rmaDetails.Select(s => s.SerialNo).ToList();
            var SNo = string.Empty;
            for (int i = 0; i < serialNos.Count; i++)
            {
                SNo += serialNos[i]+"</br>";
            }
            new EmailGenerator().ConfigMail(rmaHeader.EmailID, true, documentNo, SNo);
            return Content("<script language='javascript' type='text/javascript'>alert('RMA Number is Sent To Your Mail!');window.location = '/RMA/Inward';</script>");
            //return RedirectToAction("Inward");
        }
        public ActionResult GenerateVendorRMA(VendorRMAHeader vendorRmaHeader)
        {
            vendorRmaHeader.VendorRmaDetails = vendorRmaHeader.VendorRmaDetails.Where(x => x.IsValid == true).ToList();
            vendorRmaHeader.Status = true;
            vendorRmaHeader.CreatedBy = USER_ID;
            vendorRmaHeader.CreatedOn = UTILITY.SINGAPORETIME;
            vendorRmaHeader.ModifiedBy = USER_ID;
            vendorRmaHeader.ModifiedOn = UTILITY.SINGAPORETIME;
            vendorRmaHeader.IncidentDate = UTILITY.SINGAPORETIME;
            var result = new VendorRMAHeaderBO().SaveVendorRMAHeader(vendorRmaHeader, BRANCH_ID);

            return RedirectToAction("VendorRMA");
        }
        [HttpGet]
        public ActionResult VendorRMAOutwardList()
        {
            var list = new VendorRMAHeaderBO().GetListByBranchID(BRANCH_ID);
            return View("VendorOutwardRMA", list);
        }

        [HttpGet]
        public ActionResult OutwardList()
        {
            var list = new RMAHeaderBO().GetListByBranchID(BRANCH_ID);
            return View("OutwardList", list);
        }

        [HttpGet]
        public ActionResult GetRMAByDocumentNo(string documentNo)
        {
            RMAOutwardHeader RMAOutwardHeader = new RMAOutwardHeader();
            RMAOutwardHeader.RmaDetails = new RMAOutwardDetailBO().RMAOutWardDetailListByRMAInWardDocumentNo(documentNo, BRANCH_ID);
            RMAOutwardHeader.ReferenceNo = RMAOutwardHeader.RmaDetails.FirstOrDefault() != null ?
                                                 RMAOutwardHeader.RmaDetails.FirstOrDefault().DocumentNo : string.Empty;
            return View(RMAOutwardHeader);
        }

        [HttpGet]
        public ActionResult GetVendorRMAByDocumentNo(string documentNo)
        {
            VendorRMAOutwardHeader vendorRMAOutwardHeader = new VendorRMAOutwardHeader();
            vendorRMAOutwardHeader.VendorRmaDetails = new VendorRMAOutwardDetailBO().VendorRMAOutWardDetailListByRMAInWardDocumentNo(documentNo, BRANCH_ID);
            vendorRMAOutwardHeader.ReferenceNo = vendorRMAOutwardHeader.VendorRmaDetails.FirstOrDefault() != null ?
                                                 vendorRMAOutwardHeader.VendorRmaDetails.FirstOrDefault().DocumentNo : string.Empty;
            ViewBag.vProducts = new ProductBO().GetList()
                   .Where(x => x.Status == true)
                   .Select(x => new
                   {
                       Value = x.ProductCode,
                       Text = x.ProductCode
                   })
                   .ToList();
            return View(vendorRMAOutwardHeader);
        }


        [HttpPost]
        public ActionResult SaveRMAOutWard(RMAOutwardHeader header)
        {
            Func<RMAOutwardDetail, bool> WhereFunc = delegate (RMAOutwardDetail detail)
            {

EDU.Web/Views/RMA/EmailSent.cshtml
@{
    ViewBag.Title = "EmailSent";
}

<h2>EmailSent</h2>

EDU.Web/Views/RMA/GetRMAByDocumentNo.cshtml
@model EZY.EDU.Contract.RMAOutwardHeader
@{
    ViewBag.Title = "GetRMAByDocumentNo";
}

<section class="content">
    @using (Html.BeginForm("SaveRMAOutWard", "RMA", FormMethod.Post, new { id = "frm", name = "frm" }))
    {
    <div class="box box-default">
        <div class="box-header with-border">
            <h3 class="box-title"><i class="fa fa-list-alt" aria-hidden="true"></i>&nbsp;RMA Outward</h3>
        </div>
        <div class="box-body">
            <div class="row css10">
                <div class="col-md-2">
                    <label class="control-label pull-right">RMA No</label>
                </div>
                <div class="col-md-2">
                    @Html.TextBoxFor(x => x.ReferenceNo, new { @class = "form-control input-sm", @readonly = "readonly" })
                </div>
            </div>
            <div class="row css10">
                <div class="col-md-12">
                    <table class="table table-striped">
                        <thead>
                            <tr>
                                <th>Document No</th>
                                <th>Old Serial No</th>
                                <th>New Serial No</th>
                                <th>Product Code</th>
                                <th>Product Description</th>
                                <th>Cost</th>
                                <th>Is Credit Note</th>
                            </tr>
                        </thead>
                        <tbody>

                            @for (var i = 0; i < Model.RmaDetails.Count; i++)
                            {
                                <tr>
                                    <td>
                                        @Model.RmaDetails[i].DocumentNo
                                        @Html.HiddenFor(x => x.RmaDetails[i].DocumentNo)
                                    </td>
                                    <td>
                                        @Model.RmaDetails[i].OldSerialNo
                                        @Html.HiddenFor(x => x.RmaDetails[i].OldSerialNo)
                                    </td>
                                    <td>
                                        @Html.TextBoxFor(x => x.RmaDetails[i].NewSerialNo, new { @class = "form-control input-sm", onkeypress = "onKeyPress(event)" })
                                    </td>
                                    <td>
                                        @Model.RmaDetails[i].ProductCode
                                        @Html.HiddenFor(x => x.RmaDetails[i].ProductCode)
                                    </td>
                                    <td>
                                        @Model.RmaDetails[i].ProductDescription
                                        @Html.HiddenFor(x => x.RmaDetails[i].ProductDescription)
                                    </td>
                                    <td>
                                        @Model.RmaDetails[i].Cost
                                        @Html.HiddenFor(x => x.RmaDetails[i].Cost)
                                    </td>
                                    <td>
                                        @Html.CheckBoxFor(x => x.RmaDetails[i].IsCreditNote, new { onchange = "chkOnChanged(" + i + ")" })
                                    </td>
                                </tr>
                            }                            
                        </tbody>
                    </table>                    
                </div>
            </div>
            <div class="row css10">
                <div class="col-md-12">
                    <button class="btn btn-primary btn-sm" type="button" onclick="btnSave()"><i class="fa fa-floppy-o"></i>&nbsp;Save</button>
                    <button class="btn btn-default btn-sm" type="button" onclick="location.href = '@Url.Content("~/RMA/OutwardList")'"><i class="fa fa-backward"></i>&nbsp;Cancel</button>
                </div>                
            </div>
        </div>
    </div>
    }
</section>
@section secscripts{
    <script type="text/javascript">
        function chkOnChanged(index) {
            if ($('#RmaDetails_' + index + '__IsCreditNote').is(':checked'))
                $('#RmaDetails_' + index + '__NewSerialNo').val('').attr('readonly', 'readonly');
            else
                $('#RmaDetails_' + index + '__NewSerialNo').val('').removeAttr('readonly');
        }

        function onKeyPress(e) {
            var key = e.which;
            if (key == 13) 
            {
                var currentIndex = parseInt(e.currentTarget.id.split('_')[1]);
                $('#RmaDetails_' + currentIndex + '__IsCreditNote').prop('checked', false);
                $('#RmaDetails_' + (currentIndex + 1) + '__NewSerialNo').focus();
            }
        }

        function btnSave() {
            $('#frm').submit();
        }
    </script>
}

EDU.Web/Views/RMA/GetVendorRMAByDocumentNo.cshtml
@model EZY.EDU.Contract.VendorRMAOutwardHeader
@{
    ViewBag.Title = "GetVendorRMAByDocumentNo";
}

<section class="content">
    @using (Html.BeginForm("SaveVendorRMAOutWard", "RMA", FormMethod.Post, new { id = "frm", name = "frm" }))
    {
        <div class="box box-default">
            <div class="box-header with-border">
                <h3 class="box-title"><i class="fa fa-list-alt" aria-hidden="true"></i>&nbsp;Vendor Inward</h3>
            </div>
            <div class="box-body">
                <div class="row css10">
                    <div class="col-md-2">
                        <label class="control-label pull-right">Vendor RMA No</label>
                    </div>
                    <div class="col-md-2">
                        @Html.TextBoxFor(x => x.ReferenceNo, new { @class = "form-control input-sm", @readonly = "readonly" })
                    </div>
                </div>
                <div class="row css10">
                    <div class="col-md-12">
                        <table class="table table-striped">
                            <thead>
                                <tr>
                                    <th>Document No</th>
                                    <th>Old Serial No</th>
                                    <th>Replacement Serial No</th>
                                    <th>Product Code</th>
                                    <th>Replacement Product Code</th>
                                    <th>Product Description</th>
                                    <th>Cost</th>
                                    <th>Is Credit Note</th>                                
                                </tr>
                            </thead>
                            <tbody>

                                @for (var i = 0; i < Model.VendorRmaDetails.Count; i++)
                                {
                                    <tr>
                                        <td>
                                            @Model.VendorRmaDetails[i].DocumentNo
                                            @Html.HiddenFor(x => x.VendorRmaDetails[i].DocumentNo)
                                        </td>
                                        <td>
                                            @Model.VendorRmaDetails[i].OldSerialNo
                                            @Html.HiddenFor(x => x.VendorRmaDetails[i].OldSerialNo)
                                        </td>
                                        <td>
                                            @Html.TextBoxFor(x => x.VendorRmaDetails[i].NewSerialNo, new { @class = "form-control input-sm", onkeypress = "onKeyPress(event)" })
                                        </td>
                                        <td>
                                            @Model.VendorRmaDetails[i].ProductCode
                                            @Html.HiddenFor(x => x.VendorRmaDetails[i].ProductCode)
                                        </td>
                                        <td>
                                            @Html.DropDownListFor(x=>x.VendorRmaDetails[i].ReplacementProductCode, new SelectList(ViewBag.vProducts, "Value", "Text"), "Select Product", new { @class = "form-control input-sm" })
                                        </td>
                                        <td>
                                            @Model.VendorRmaDetails[i].ProductDescription
                                            @Html.HiddenFor(x => x.VendorRmaDetails[i].ProductDescription)
                                        </td>
                                        <td>
                                            @Model.VendorRmaDetails[i].Cost
                                            @Html.HiddenFor(x => x.VendorRmaDetails[i].Cost)
                                        </td>
                                        <td>
                                            @Html.CheckBoxFor(x => x.VendorRmaDetails[i].IsCreditNote, new { onchange = "chkOnChanged(" + i + ")" })
                                        </td>                                        
                                    </tr>
                                }
                            </tbody>
                        </table>
                    </div>
                </div>
                <div class="row css10">
                    <div class="col-md-12">
                        <button class="btn btn-primary btn-sm" type="button" onclick="btnSave()"><i class="fa fa-floppy-o"></i>&nbsp;Save</button>
                        <button class="btn btn-default btn-sm" type="button" onclick="location.href = '@Url.Content("~/RMA/VendorRMAOutwardList")'"><i class="fa fa-backward"></i>&nbsp;Cancel</button>
                    </div>
                </div>
            </div>
        </div>
    }
</section>
@section secscripts{
    <script type="text/javascript">
        function chkOnChanged(index) {
            if ($('#VendorRmaDetails_' + index + '__IsCreditNote').is(':checked'))
                $('#VendorRmaDetails_' + index + '__NewSerialNo').val('').attr('readonly', 'readonly');
            else
                $('#VendorRmaDetails_' + index + '__NewSerialNo').val('').removeAttr('readonly');
        }

        function onKeyPress(e) {
            var key = e.which;
            if (key == 13)
            {
                var currentIndex = parseInt(e.currentTarget.id.split('_')[1]);
                $('#VendorRmaDetails_' + currentIndex + '__IsCreditNote').prop('checked', false);
                $('#VendorRmaDetails_' + (currentIndex + 1) + '__NewSerialNo').focus();
            }
        }

        function btnSave() {
            $('#frm').submit();
        }
    </script>
}

EDU.Web/Views/RMA/Outword.cshtml
@model EZY.EDU.Contract.RMAOutwardHeader
@{
    ViewBag.Title = "Outword";
}
@section seccss{
    @*<link href="@Url.Content("~/Css/datepicker3.css")" rel="stylesheet" />
    <link href="@Url.Content("~/Css/bootstrap-timepicker.css")" rel="stylesheet" />*@
<link href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datetimepicker/4.17.47/css/bootstrap-datetimepicker.css" rel="stylesheet">
}


@using (Html.BeginForm("Outword", "RMA", FormMethod.Post, new { id = "frm", name = "frm", enctype = "multipart/form-data" }))
{
    <section class="content">

        <div class="box box-default">
            <div class="box-header with-border">
                <h3 class="box-title"><i class="fa fa-list-alt" aria-hidden="true"></i>&nbsp;Material Inward </h3>
            </div>
            <div class="box-body">
                <div class="row css10">
                    <div class="col-md-3">
                        <label class="control-label pull-right">Document Number&nbsp; <span class="error-req">*</span></label>
                    </div>
                    <div class="col-md-4">
                        @Html.TextBoxFor(x => x.DocumentNo,
                         new
                         {
                             @class = "form-control input-sm",
                             placeholder = "Document Number"
                         })
                    </div>
                </div>
                <div class="row css10">
                    <div class="col-md-3">
                        <label class="control-label pull-right">Document Date&nbsp; <span class="error-req">*</span></label>
                    </div>
                    <div class="col-md-4">
                        @Html.TextBoxFor(x => x.DocumentDate,
                         new
                         {
                             @class = "form-control input-sm",
                             placeholder = "Document Number"
                         })
                    </div>
                </div>

                <div class="row css10">
                    <div class="col-md-3">
                        <label class="control-label pull-right">Document Date&nbsp; <span class="error-req">*</span></label>
                    </div>
                    <div class="col-md-4">
                        @Html.TextBoxFor(x => x.DocumentDate,
                         new
                         {
                             @class = "form-control input-sm",
                             placeholder = "Document Date"
                         })
                    </div>
                </div>
                <div class="row css10">
                    <div class="col-md-3">
                        <label class="control-label pull-right">Reference Number&nbsp; <span class="error-req">*</span></label>
                    </div>
                    <div class="col-md-4">
                        @Html.TextBoxFor(x => x.ReferenceNo,
                         new
                         {
                             @class = "form-control input-sm",
                             placeholder = "Reference Number"
                         })
                    </div>
                </div>


                <div class="box-footer">
                    @*@if (UTILITY.HasRight("VendorInvoiceSave", "Action"))
                        {*@

                    <button type="button" onclick="SaveRMAOutWord()" class="btn btn-danger btn-sm btn-frmt green">
                        <i class="fa fa-pencil-square"></i>&nbsp;Save RMA Outword
                    </button>
                    @*}*@
                    <button type="button" onclick="location.href = '@Url.Content("~/Invoice/OutwordList")'" class="btn btn-default btn-sm btn-frmt ">
                        <i class="fa fa-times"></i>&nbsp;Cancel
                    </button>
                </div>
                <div class="overlay" style="display:none;">
                    <i class="fa fa-refresh fa-spin"></i>
                </div>
            </div>


        </div>
    </section>
    <div id="invoiceHeaderDetailDiv">
    </div>

}

<div id="ScanProductsModal" class="modal fade" role="dialog">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4 class="modal-title">Scan Products</h4>
            </div>
            <div class="modal-body" id="ProductModalBody">
                <div class="row" style="margin-bottom:10px;">
                    <div class="col-md-2">
                        <label class="control-label pull-right">Serial Nos</label>
                    </div>
                    <div class="col-md-10">
                        <textarea class="form-control input-sm" rows="10" id="serialNos" name="serialNos"></textarea>
                    </div>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" onclick="SaveSerialsNo()" class="btn btn-danger btn-frmt green btn-sm">
                    <i class="fa fa-floppy-o"></i>&nbsp;Save
                </button>

                <button type="reset" class="btn btn-default btn-frmt btn-sm" data-dismiss="modal">
                    <i class="fa fa-times"></i>Cancel
                </button>
            </div>
        </div>
    </div>
</div>

@section secscripts{
    <script src="@Url.Content("~/Scripts/moment.min.js")"></script>
    <script src="@Url.Content("~/Scripts/bootstrap-datetimepicker.js")"></script>
    <script type="text/javascript">
        $('#frm').validate({
            rules: {
                DocumentNo: {
                    required: true
                },
                DocumentDate: {
                    required: true
                },
                ReferenceNo: {
                    required: true
                }
            }
        });

        @if(Model.RmaDetails == null)
        {
            <text>
        $('input[name^="file"]').each(function () {
            $(this).rules('add', {
                required: true
            })
        });
        </text>
        }


        function ProcessVendorInvoice() {
            if ($('#frm').valid()) {
                $('#frm').submit();
            }
        }

        function SaveRMAOutWord() {
            if ($('#frm').valid()) {
                //if (confirm("Are you sure ? You want to save \nProduct Category: " + $('#ProductCategory option:selected').text()
                //    + "\nProduct Code: " + $('#ProductCode').val() + "\nModels: " + $('#ModelNo option:selected').text() + "\nVendor / Supplier Name: " + $('#CustomerCode').val()
                //    + "\nInvoice No: " + $('#InvoiceNo').val() + "\nQuantity: " + $('#Quantity').val() + "\nUnit Price: " + $('#UnitPrice').val())) {
                $('#frm').attr('action', '@Url.Content("~/Invoice/SaveRMAOutWord")');
                $('#frm').submit();
                //}
            }
        };

        function WarrantyPeriod_OnChange(el) {
            var months = parseInt(el.value);
            var invoiceDate = $('#InvoiceDate').val();

            var expiryDate = moment(invoiceDate, 'DD/MM/YYYY').add(months, 'M');
            $('#expirtyDtMsg').html('Your invoice will expire on ' + moment(expiryDate).format('DD/MM/YYYY'));

        }

        function ScanSerialNo() {
            $('#ScanProductsModal').modal('show');
            setTimeout(function () {
                $('#serialNos').focus();
            }, 900);

        }

        function fileChanged(el) {
            var file = el.files[0];
            if (file != null) {
                $('#scanBtn').attr('disabled', 'disabled');
            }
        }

        //function SaveSerialsNo() {
        //    var settings = $('#frm').validate().settings;
        //    settings.rules.file = { required: false };

        //    var serialNos = $('#serialNos').val().split(/\n/);

        //    var invoiceDetailHtml = '';
        //    $.each(serialNos, function (index, item) {
        //        if (item != '') {
        //            invoiceDetailHtml += '<input type="hidden" id="InvoiceDetailItems_' + index + '__SerialNo" name="InvoiceDetailItems[' + index + '].SerialNo" value="' + item + '" />'
        //        }
        //    });
        //    $('#invoiceHeaderDetailDiv').html(invoiceDetailHtml);
        //    $('#fileupload').attr('disabled', 'disabled');
        //    $('#ScanProductsModal').modal('hide');
        //}
    </script>
    <!--http://stackoverflow.com/questions/20929355/jquery-validate-input-file-type-->
    <!--http://stackoverflow.com/questions/974079/setting-mime-type-for-excel-document-->
}