EDU.Web/Models/Revenue.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDU.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Revenue
    {
        public int RevenueId { get; set; }
        public short Country { get; set; }
        public string CountryName { get; set; }
        public int Product { get; set; }
        public string ProductName { get; set; }
        public string CurrencyCode { get; set; }
        public decimal CurrencyExRate { get; set; }
        public int Year { get; set; }
        public decimal YearlyTarget { get; set; }
        public decimal HalfYearlyTarget { get; set; }
        public decimal QuarterlyTarget { get; set; }
        public decimal MonthlyTarget { get; set; }
        public decimal YearlyTargetAmt { get; set; }
        public decimal HalfYearlyTargetAmt { get; set; }
        public decimal QuarterlyTargetAmt { get; set; }
        public decimal MonthlyTargetAmt { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<bool> IsActive { get; set; }
    }
}

EDU.Web/Controllers/RevenueController.cs
using EDU.Web.Models;
using EDU.Web.ViewModels.RevenueModel;
using EZY.EDU.BusinessFactory;
using EZY.EDU.Contract;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace EDU.Web.Controllers
{
    public class RevenueController : BaseController
    {
        EducationEntities dbContext = new EducationEntities();

        [HttpPost]
        public JsonResult SaveRevenueInfo(Revenue revenue)
        {
            revenue.Year = revenue.Year == 0 ? DateTime.Now.Year : revenue.Year;

            revenue.HalfYearlyTarget = revenue.YearlyTarget / 2;
            revenue.QuarterlyTarget = revenue.YearlyTarget / 4;
            revenue.MonthlyTarget = revenue.YearlyTarget / 12;

            revenue.YearlyTargetAmt = revenue.YearlyTarget * revenue.CurrencyExRate;

            revenue.HalfYearlyTargetAmt = revenue.YearlyTargetAmt / 2;
            revenue.QuarterlyTargetAmt = revenue.YearlyTargetAmt / 4;
            revenue.MonthlyTargetAmt = revenue.YearlyTargetAmt / 12;
            revenue.IsActive = true;

            try
            {
                if (revenue.RevenueId == -1)
                {
                    revenue.CreatedBy = USER_ID;
                    revenue.CreatedOn = UTILITY.SINGAPORETIME;
                    dbContext.Revenues.Add(revenue);
                }
                else
                {
                    Revenue revenueInfo = dbContext.Revenues.
                       Where(x => x.RevenueId == revenue.RevenueId).FirstOrDefault();

                    revenueInfo.CurrencyExRate = revenue.CurrencyExRate;

                    revenueInfo.YearlyTarget = revenue.YearlyTarget;
                    revenueInfo.HalfYearlyTarget = revenue.HalfYearlyTarget;
                    revenueInfo.QuarterlyTarget = revenue.QuarterlyTarget;
                    revenueInfo.MonthlyTarget = revenue.MonthlyTarget;

                    revenueInfo.YearlyTargetAmt = revenue.YearlyTargetAmt;

                    revenueInfo.HalfYearlyTargetAmt = revenue.HalfYearlyTargetAmt;
                    revenueInfo.QuarterlyTargetAmt = revenue.QuarterlyTargetAmt;
                    revenueInfo.MonthlyTargetAmt = revenue.MonthlyTargetAmt;
                    revenueInfo.IsActive = true;

                    revenueInfo.ModifiedBy = USER_ID;
                    revenueInfo.ModifiedOn = UTILITY.SINGAPORETIME;

                    dbContext.Entry(revenueInfo).State = EntityState.Modified;
                }

                dbContext.SaveChanges();
            }
            catch (Exception ex)
            {
                throw ex;
            }

            string message = "Saved Successfully.";
            return Json(message, JsonRequestBehavior.AllowGet);
        }


        [HttpPost]
        public JsonResult updateRevenueInfoByExRate(Revenue revenue)
        {
            List<Revenue> RevenueList = dbContext.Revenues.Where(x => x.IsActive == true && x.Country == revenue.Country && x.Year == revenue.Year).ToList(); //&& x.CurrencyCode == revenue.CurrencyCode

            try
            {
                foreach (Revenue rv in RevenueList)
                {
                    rv.CurrencyExRate = revenue.CurrencyExRate;

                    rv.YearlyTargetAmt = rv.YearlyTarget * revenue.CurrencyExRate;

                    rv.HalfYearlyTargetAmt = rv.YearlyTargetAmt/2;
                    rv.QuarterlyTargetAmt = rv.YearlyTargetAmt/4;
                    rv.MonthlyTargetAmt = rv.YearlyTargetAmt/12;
                    rv.IsActive = true;

                    rv.ModifiedBy = USER_ID;
                    rv.ModifiedOn = UTILITY.SINGAPORETIME;

                    dbContext.Entry(rv).State = EntityState.Modified;
                }

                dbContext.SaveChanges();
            }
            catch (Exception ex)
            {
                throw ex;
            }

            string message = "Currency Ex. Rate Updated Successfully.";
            return Json(message, JsonRequestBehavior.AllowGet);
        }


        [HttpGet]
        public JsonResult GetCurrency(Int16 Id)
        {
            var country = new BranchBO().GetList().Where(x => x.IsActive == true && x.BranchID == Id).FirstOrDefault();
            var currencyCode = new LookupBO().GetList().Where(x => x.LookupCategory == "Currency" && x.MappingCode == country.BranchCode).FirstOrDefault();

            return Json(currencyCode == null ? "" : currencyCode.LookupCode, JsonRequestBehavior.AllowGet);

        }

        [HttpGet]
        public ActionResult RevenueList(Int16 country, int year)
        {
            List<Revenue> List = GetList(country, year);
            return View(List);
        }

        private List<Revenue> GetList(short country, int year)
        {
            List<Revenue> RevenueList = dbContext.Revenues.Where(x => x.IsActive == true && x.Country == country && x.Year == year).ToList();
            var productList = new EduProductBO().GetList().Where(x => x.IsActive == true).ToList();

            ViewData["CountryData"] = new BranchBO().GetList().Where(x => x.IsActive == true).ToList();
            ViewData["CurrencyList"] = new LookupBO().GetList().Where(x => x.LookupCategory == "Currency").ToList();

            var countryrow = ((List<Branch>)ViewData["CountryData"]).Where(x => x.IsActive == true && x.BranchID == country).FirstOrDefault();
            var currencyCode = ((List<Lookup>)ViewData["CurrencyList"]).Where(x => x.LookupCategory == "Currency" && x.MappingCode == countryrow.BranchCode).FirstOrDefault();

            foreach (EduProduct ep in productList)
            {
                if (RevenueList.Where(x => x.Product == ep.Id).Count() == 0)
                    RevenueList.Add(new Revenue() { Product = ep.Id, ProductName = ep.ProductName, RevenueId = -1, CurrencyCode = currencyCode == null ? "" : currencyCode.LookupCode });
            }
            return RevenueList;
        }
    }
}

EDU.Web/Views/Revenue/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Index</h2>

EDU.Web/Views/Revenue/RevenueList.cshtml
@model IEnumerable<EDU.Web.Models.Revenue>
@{
    ViewBag.Title = "RevenueList";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<style>
    .input-xs {
        display: block;
        width: 75%;
        height: 25px;
        font-size: 14px !important;
        color: #000;
        font-weight: 600;
        background-color: #fff;
        background-image: none;
        border: 1px solid #ccc;
    }

    table {
        border: 1px solid lightgray;
    }

    .tdheight {
        min-height: 25px !important;
    }
</style>
<form name="frmRevenue" id="frmRevenue">
    <section class="content">
        <div class="box box-dnex">
            <div class="box-header with-border">
                <div class="row">
                    <section class="content-header">
                        <ol class="breadcrumb">
                            <li><a href='@Url.Content("~/Home/Education")'><i class="fa fa-dashboard"></i> Home</a></li>
                            <li class="active">Revenue</li>
                        </ol>
                    </section>
                </div>
            </div>
            <div class="box-body">
                <div class="row">
                    <div class="col-md-2"></div>
                    <div class="col-md-2">
                        @Html.DropDownListFor(x => x.FirstOrDefault().Country,
                             new SelectList((List<EZY.EDU.Contract.Branch>)ViewData["CountryData"], "BranchID", "BranchName"),
                             "Select Country", new { @class = "form-control input-sm", onchange = "CountryChange(this);" })
                    </div>
                    <div class="col-md-1">
                        @Html.DropDownListFor(x => x.FirstOrDefault().CurrencyCode,
                             new SelectList((List<EZY.EDU.Contract.Lookup>)ViewData["CurrencyList"], "LookupCode", "LookupCode"),
                             "Select Currency", new { @class = "form-control input-sm" })
                    </div>
                    @*<div class="col-md-2">
                            <label class="control-label">CONVERSION RATE</label>
                        </div>*@
                    <div class="col-md-2">
                        @Html.TextBoxFor(x => x.FirstOrDefault().CurrencyExRate, "{0:#.#}",
                            new { placeholder = "CONVERSION RATE", @class = "form-control input-sm numCss" })
                    </div>
                    <div class="col-md-3"></div>
                </div>
                <div class="row css10">
                    <div class="col-md-6">
                        @{
                            var grid = new WebGrid(Model);
                        }
                        <div id="gridContent">
                            @grid.GetHtml(
                                     tableStyle: "table table-striped",
                                     mode: WebGridPagerModes.All,
                                     columns:
                                         grid.Columns(
                                         grid.Column("ProductName", "Product Name", format: @<text>  <span class="display-mode">@item.ProductName </span> <label id="lblProductName" class="edit-mode">@item.ProductName</label> </text>, style: ""),
                                         grid.Column("YearlyTarget", "YearlyTarget", format: @<text> <span class="display-mode"> <label id="lblYearlyTarget">@(item.HalfYearlyTarget > 0 ? item.YearlyTarget.ToString("0.00") : "")</label> </span>  <input type="text" name="YearlyTarget" id="YearlyTarget" value="@(item.HalfYearlyTarget > 0 ? item.YearlyTarget.ToString("0.00") : "")" class="edit-mode numCss input-xs" /> </text>, style: ""),
                                         grid.Column("HalfYearlyTarget", "Half Yearly", format: @<text>  <span class="display-mode">@(item.HalfYearlyTarget > 0 ? item.HalfYearlyTarget.ToString("0.00") : "") </span> <label id="lblHalfYearlyTarget" class="edit-mode">@(item.HalfYearlyTarget > 0 ? item.HalfYearlyTarget.ToString("0.00") : "")</label> </text>, style: ""),
                                         grid.Column("QuarterlyTarget", "Quarterly", format: @<text>  <span class="display-mode">@(item.QuarterlyTarget > 0 ? item.QuarterlyTarget.ToString("0.00") : "") </span> <label id="lblQuarterlyTarget" class="edit-mode">@(item.QuarterlyTarget > 0 ? item.QuarterlyTarget.ToString("0.00") : "")</label> </text>, style: ""),
                                         grid.Column("MonthlyTarget", "Monthly", format: @<text>  <span class="display-mode">@(item.MonthlyTarget > 0 ? item.MonthlyTarget.ToString("0.00") : "") </span> <label id="lblMonthlyTarget" class="edit-mode">@(item.MonthlyTarget > 0 ? item.MonthlyTarget.ToString("0.00") : "")</label> </text>, style: ""),
                                         grid.Column("Action", format: @<text>
                                @if (Session["UserID"].ToString().ToUpper() == "ADMIN")
                                                {
                            <button type="button" class="edit-user display-mode btn btn-primary btn-xs"><i class="fa fa-pencil-square-o"></i></button>
                                                }
                                <button type="button" class="save-user edit-mode btn btn-success btn-xs" onclick="SaveRevenue(@item.RevenueId,@item.Product,@item.Year,'@item.ProductName')"><i class="fa fa-floppy-o"></i></button>
                                <button type="button" class="cancel-user edit-mode btn btn-default btn-xs"><i class="fa fa-times"></i></button>
                                        </text>, style: "col3Width", canSort: false)
                                        ))
                        </div>
                    </div>

                    <div class="col-md-6">
                        <table class="table table-striped" id="tblProductRevenue">
                            <thead>
                                <tr>
                                    <th>Product</th>
                                    <th>Yearly Target</th>
                                    <th>Half yearly</th>
                                    <th>Quarterly</th>
                                    <th>Monthly</th>
                                </tr>
                            </thead>
                            <tbody>
                                @for (var i = 0; i < Model.Count(); i++)
                                {
                                <tr style="height: 39.5px;">
                                    <td>@Model.ElementAt(i).ProductName</td>
                                    <td>@(Model.ElementAt(i).YearlyTargetAmt > 0 ? Model.ElementAt(i).YearlyTargetAmt.ToString("0.00") : "")</td>
                                    <td>@(Model.ElementAt(i).HalfYearlyTargetAmt > 0 ? Model.ElementAt(i).HalfYearlyTargetAmt.ToString("0.00") : "")</td>
                                    <td>@(Model.ElementAt(i).QuarterlyTargetAmt > 0 ? Model.ElementAt(i).QuarterlyTargetAmt.ToString("0.00") : "")</td>
                                    <td>@(Model.ElementAt(i).MonthlyTargetAmt > 0 ? Model.ElementAt(i).MonthlyTargetAmt.ToString("0.00") : "")</td>
                                </tr>
                                }
                            </tbody>
                        </table>
                    </div>
                </div>
                <div class="row css10">
                    <div class="col-md-12">
                        @if (Session["UserID"].ToString().ToUpper() == "ADMIN")
                        {
                        <button type="button" onclick="updateRevenueInfoByExRate()" class="btn btn-primary btn-sm"><i class="fa fa-floppy-o"></i>&nbsp;Update</button>
                        }
                    </div>
                </div>
            </div>
        </div>
    </section>
</form>

@section secscripts {
    <script type="text/javascript">
    @if(@Model.FirstOrDefault().Country != 10 && Session["UserID"].ToString().ToUpper() != "ADMIN")
    {
        <text>
    $(function () {
        $('#Country, #CurrencyCode, #CurrencyExRate').attr('disabled', 'disabled');
    });
        </text>
    }


    $('#frmRevenue').validate({
        rules: {
            'Country': {
                required: true
            },
            'CurrencyCode': {
                required: true
            },
            'CurrencyExRate': {
                required: true
            },
            'YearlyTarget': {
                required: true
            }
        }
    });

        function updateRevenueInfoByExRate() {
            if ($('#frmRevenue').valid()) {
                var Revenue =
                    {
                        "CurrencyExRate": $('#CurrencyExRate').val(),
                        "Country": $('#Country').val(),
                        "CurrencyCode": $('#CurrencyCode').val(),
                        "Year": 2017
                    };
                $.ajax({
                    url: '@Url.Content("~/Revenue/updateRevenueInfoByExRate/")',
                    data: JSON.stringify(Revenue),
                    type: 'POST',
                    contentType: 'application/json; charset=utf-8',
                    success: function (data) {
                        alert(data);
                        location.reload(true);
                    }
                });
            }
        }

    var Product = null;
    var ProductName = null;
    var RevenueId = null;
    var Year = null;

    function SaveRevenue(revenueId, product, year, productName)
    {
         Product = product;
         ProductName = productName;
         RevenueId = revenueId;
         Year = year;
    }
    function CountryChange(el) {
        if (el.value) {
            window.location = '@Url.Action("RevenueList", "Revenue", new { country = "", year="" })' + '?country=' + el.value + '&year=' + 2017;
                @*$.ajax({
                    url: '@Url.Content("~/Revenue/GetCurrency?Id=")' + el.value,
                    method: 'GET',
                    contentType: 'application/json',
                    success: function (data) {
                        debugger;
                        $("#CurrencyCode").val(data);
                    },
                    error: function (err) {
                    }
                });*@
            }
        else
            {
                $("#CurrencyCode").val('');
            }
    };

    $(function () {

        $("#CurrencyCode").val('@Model.FirstOrDefault().CurrencyCode');

        $('.edit-mode').hide();
        $('.edit-user, .cancel-user').on('click', function () {
            var tr = $(this).parents('tr:first');
            tr.find('.edit-mode, .display-mode').toggle();
        });

        $('.save-user').on('click', function () {
            if ($('#frmRevenue').valid()) {
            var tr = $(this).parents('tr:first');

            //var Product = tr.find("#hdnProduct").val();
            //var ProductName = tr.find("#hdnProductName").val();
            var YearlyTarget = tr.find("#YearlyTarget").val();
            //var RevenueId = tr.find("#hdnRevenueId").val();
            //var Year = tr.find("#hdnYear").val();

            tr.find('.edit-mode, .display-mode').toggle();
            var Revenue =
                {
                    "RevenueId": RevenueId,
                    "Product": Product,
                    "ProductName": ProductName,
                    "YearlyTarget": YearlyTarget,
                    "CurrencyExRate": $('#CurrencyExRate').val(),
                    "Country": $('#Country').val(),
                    "CountryName": $("#Country option:selected").text(),
                    "CurrencyCode": $('#CurrencyCode').val(),
                    "Year": Year
                };
            $.ajax({
                url: '@Url.Content("~/Revenue/SaveRevenueInfo/")',
                data: JSON.stringify(Revenue),
                type: 'POST',
                contentType: 'application/json; charset=utf-8',
                success: function (data) {
                    alert(data);
                    location.reload(true);
                }
            });
        }
        });
    })
    </script>
}

EDU.Web/Views/Revenue/RevenueList1.cshtml
@{
    ViewBag.Title = "RevenueList";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@section seccss{
    <link href="@Url.Content("~/Css/dataTables.bootstrap.css")" rel="stylesheet" />
    <link href="@Url.Content("~/Css/dataTables.responsive.css")" rel="stylesheet" />
}
<section class="content">
    <div class="box box-dnex">
        <div class="box-header with-border">
            <div class="row">
                <section class="content-header">
                    @*<ol class="breadcrumb">
                        <li><a href='@Url.Content("~/Home/Education")'><i class="fa fa-dashboard"></i> Home</a></li>
                        <li><a href='@Url.Content("~/Trainer/TrainersList")'>Trainers List</a></li>
                    </ol>*@
                </section>
            </div>
            <div class="box-tools">
                @if (Session["UserID"].ToString().ToUpper() == "ADMIN")
                {
                    <button class="btn btn-default btn-sm" type="button" onclick="location.href = '@Url.Content("~/Revenue/Index?Id=-1")'">
                        <i class="fa fa-plus"></i>&nbsp;Add New Revenue
                    </button>
                }
            </div>
        </div>
    </div>
    <div class="box-body">
        <div class="row" style="margin-top:10px;">
            <div class="col-md-12">
                <table class="table table-striped" id="tblTrainer">
                    <thead>
                        <tr>
                            <th>#</th>
                            <th>Product</th>
                            <th>Country</th>
                            <th>Yearly Target</th>
                            <th>Half yearly</th>
                            <th>Quarterly</th>
                            <th>Monthly</th>
                        </tr>
                    </thead>
                    <tbody>
                        @for (int i = 0; i < Model.Count(); i++)
                        {
                            <tr>
                                <td>@(i + 1)</td>
                                <td>@Model.ElementAt(i).Product</td>
                                <td>@Model.ElementAt(i).Country</td>
                                <td>
                                    <button type="button" class="btn btn-primary btn-sm"
                                            onclick="location.href ='@Url.Content("~/Trainer/Index?Id=" + Model.ElementAt(i).TrianerId)'">
                                        Edit
                                    </button>
                                    <button type="button" class="btn btn-danger btn-sm"
                                            onclick="DeleteTrainer(@Model.ElementAt(i).TrianerId)">
                                        Delete
                                    </button>
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>

        </div>

        </div>
</section>